"""
Page 4 — Health Impact Assessment
Multi-class health impact prediction with ML + Deep Learning (ANN) support.
Includes: Model Comparison | ANN Prediction | Confusion Matrix | Classification Report | Architecture Info
"""

import sys
import json
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pandas as pd
import streamlit as st

from utils.config import HEALTH_IMPACT_FEATURES, COLORS, LOGS_DIR, REPORTS_DIR
from utils.config import (
    HEALTH_IMPACT_MODEL_PATH, HEALTH_IMPACT_SCALER_PATH, HEALTH_IMPACT_ENCODER_PATH,
    HEALTH_IMPACT_ANN_HISTORY_PATH, HEALTH_IMPACT_ANN_CONFIG_PATH,
)
from utils.validators import validate_health_inputs, format_validation_errors
from utils.visualization import plot_prediction_probabilities
from utils.model_utils import load_model

st.set_page_config(page_title="Health Impact — EIA", page_icon="🫁", layout="wide")
css_path = Path(__file__).parent.parent / "assets" / "css" / "style.css"
if css_path.exists():
    with open(css_path) as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)


# ─── Cached loaders ───────────────────────────────────────────────────────────

@st.cache_resource
def get_health_artifacts():
    """Load and cache best ML model artifacts."""
    return {
        "model": load_model(HEALTH_IMPACT_MODEL_PATH, "health_impact_model"),
        "scaler": load_model(HEALTH_IMPACT_SCALER_PATH, "health_impact_scaler"),
        "encoder": load_model(HEALTH_IMPACT_ENCODER_PATH, "health_impact_encoder"),
    }


@st.cache_resource
def get_ann_artifacts():
    """Load and cache ANN model artifacts (PyTorch)."""
    from utils.model_utils import load_ann_model, load_model as lm
    from utils.config import HEALTH_IMPACT_ANN_PATH, HEALTH_IMPACT_ANN_PREPROCESSOR_PATH
    ann_model = load_ann_model(HEALTH_IMPACT_ANN_PATH, HEALTH_IMPACT_ANN_CONFIG_PATH)
    preprocessor = lm(HEALTH_IMPACT_ANN_PREPROCESSOR_PATH, "ann_preprocessor")
    config: dict = {}
    if HEALTH_IMPACT_ANN_CONFIG_PATH.exists():
        with open(HEALTH_IMPACT_ANN_CONFIG_PATH, "r", encoding="utf-8") as fh:
            config = json.load(fh)
    return {"model": ann_model, "preprocessor": preprocessor, "config": config}


# ─── Header ──────────────────────────────────────────────────────────────────
st.markdown("""
<div class='page-header'>
    <h1 class='page-title'>🫁 Health Impact Assessment</h1>
    <p class='page-subtitle'>Predict health risk category from air quality and environmental parameters</p>
</div>
""", unsafe_allow_html=True)

# ─── MANDATORY HEALTH DISCLAIMER ─────────────────────────────────────────────
st.markdown("""
<div class='health-disclaimer'>
    <h3 style='color:#f87171; margin-top:0;'>⚠️ IMPORTANT HEALTH &amp; MEDICAL DISCLAIMER</h3>
    <p>The Health Impact predictions generated by this application are:</p>
    <ul>
        <li>📊 <strong>ANALYTICAL ESTIMATES</strong> based on air quality data ONLY</li>
        <li>❌ <strong>NOT</strong> medical diagnoses or professional medical advice</li>
        <li>❌ <strong>NOT</strong> a substitute for consultation with healthcare professionals</li>
        <li>⚠️ Subject to model limitations and data quality issues</li>
    </ul>
    <p><strong>This application should NOT be used for:</strong></p>
    <ul>
        <li>✗ Making medical decisions without professional consultation</li>
        <li>✗ Diagnosing health conditions</li>
        <li>✗ Replacing professional medical advice</li>
    </ul>
    <p style='color:#fca5a5; font-weight:600; margin-bottom:0;'>
        ✓ Use predictions as a general environmental awareness tool only.<br>
        ✓ Always consult qualified healthcare professionals for medical decisions.
    </p>
</div>
""", unsafe_allow_html=True)

arts = get_health_artifacts()
ann_arts = get_ann_artifacts()
model_ready = arts["model"] is not None
ann_ready = ann_arts["model"] is not None and ann_arts["preprocessor"] is not None

if not model_ready:
    st.warning("⏳ Health Impact ML model not found. Please run: `python src/health_impact_model.py`")

# ─── About This Model ─────────────────────────────────────────────────────────
with st.expander("ℹ️ About This Model", expanded=False):
    st.markdown("""
    Four **Machine Learning** models and one **Deep Learning** model were trained and compared.
    The best model was selected automatically by ROC-AUC → F1 → Accuracy.

    | Model | Type | Notes |
    |-------|------|-------|
    | Logistic Regression | ML | Baseline; interpretable |
    | Decision Tree | ML | Interpretable; may overfit |
    | Random Forest | ML | Ensemble; robust |
    | XGBoost | ML | Gradient boosting |
    | **ANN (PyTorch)** | **DL** | **Artificial Neural Network** |

    **Evaluation:** 5-fold stratified CV · Accuracy · F1 · ROC-AUC · Precision · Recall  
    **Target:** HealthImpactClass (Low / Moderate / High / Severe / Very High)
    """)

# ─── ANN Architecture ─────────────────────────────────────────────────────────
with st.expander("🧠 ANN Architecture", expanded=False):
    ann_config = ann_arts.get("config", {})
    input_dim = ann_config.get("input_dim", "?")
    num_classes = ann_config.get("num_classes", "?")
    feature_names = ann_config.get("feature_names", [])
    class_names_cfg = ann_config.get("class_names", [])
    train_t = ann_config.get("train_time_seconds", None)

    st.markdown(f"""
    <div style='background:rgba(30,41,59,0.8);border-radius:14px;padding:1.5rem;border:1px solid #334155;'>
        <h4 style='color:#00d4aa;margin-top:0;'>PyTorch Multilayer Perceptron</h4>
        <table style='width:100%;border-collapse:collapse;font-size:0.9rem;'>
            <tr><td style='color:#94a3b8;padding:4px 0;'>Framework</td><td style='color:#f8fafc;font-weight:600;'>PyTorch</td></tr>
            <tr><td style='color:#94a3b8;padding:4px 0;'>Input Dimension</td><td style='color:#f8fafc;font-weight:600;'>{input_dim} features</td></tr>
            <tr><td style='color:#94a3b8;padding:4px 0;'>Output Classes</td><td style='color:#f8fafc;font-weight:600;'>{num_classes} ({", ".join(class_names_cfg) if class_names_cfg else "?"})</td></tr>
            <tr><td style='color:#94a3b8;padding:4px 0;'>Training Time</td><td style='color:#f8fafc;font-weight:600;'>{f"{train_t:.1f}s" if train_t else "N/A"}</td></tr>
            <tr><td style='color:#94a3b8;padding:4px 0;'>Saved Format</td><td style='color:#f8fafc;font-weight:600;'>.pt (state_dict)</td></tr>
        </table>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("**Layer Architecture:**")
    layers = [
        ("Dense", "Input → 128", "ReLU + BatchNorm + Dropout(0.3)"),
        ("Dense", "128 → 64",   "ReLU + BatchNorm + Dropout(0.2)"),
        ("Dense", "64 → 32",    "ReLU"),
        ("Output", f"32 → {num_classes}", "Softmax (CrossEntropyLoss)"),
    ]
    for layer_type, dims, activation in layers:
        st.markdown(
            f"<div style='background:rgba(0,212,170,0.07);border-left:3px solid #00d4aa;"
            f"padding:0.5rem 1rem;margin:0.3rem 0;border-radius:0 8px 8px 0;font-size:0.88rem;'>"
            f"<strong style='color:#00d4aa;'>{layer_type}</strong> &nbsp; {dims} &nbsp;"
            f"<span style='color:#94a3b8;'>→ {activation}</span></div>",
            unsafe_allow_html=True,
        )

    if feature_names:
        with st.expander("📋 Feature List", expanded=False):
            st.write(feature_names)

# ─── Model Comparison & ANN Analysis ─────────────────────────────────────────
with st.expander("📊 Model Comparison & AI Analysis", expanded=False):
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots

    st.markdown("### 🏆 Full Model Comparison")
    log_path = LOGS_DIR / "health_impact_model_metrics.json"

    if log_path.exists():
        with open(log_path, "r") as f:
            metrics_data = json.load(f)

        best_overall = metrics_data.get("best_model_overall", metrics_data.get("best_model", "?"))
        best_type = metrics_data.get("best_model_type", "")
        st.success(f"🏆 **Best Model:** {best_overall}  {f'({best_type})' if best_type else ''}")

        # Use full_comparison if available, else fallback to comparison
        comp_list = metrics_data.get("full_comparison", metrics_data.get("comparison", []))

        if comp_list:
            comp_df = pd.DataFrame(comp_list)

            # Normalise column names
            col_map = {
                "model_name": "Model", "accuracy": "Accuracy",
                "precision_weighted": "Precision", "recall_weighted": "Recall",
                "f1_weighted": "F1 (Weighted)", "roc_auc": "ROC AUC",
                "cv_mean": "CV Mean", "cv_std": "CV Std",
                "train_time": "Train Time (s)", "predict_time": "Predict Time (s)",
                # already normalised keys (from full_comparison)
                "Model": "Model", "Accuracy": "Accuracy",
                "Precision": "Precision", "Recall": "Recall",
                "F1 (Weighted)": "F1 (Weighted)", "ROC AUC": "ROC AUC",
            }
            comp_df = comp_df.rename(columns={k: v for k, v in col_map.items() if k in comp_df.columns})

            # Select display columns in order
            display_cols = [c for c in [
                "Model", "ROC AUC", "F1 (Weighted)", "Accuracy",
                "Precision", "Recall", "CV Mean", "CV Std",
                "Train Time (s)", "Predict Time (s)",
            ] if c in comp_df.columns]

            format_spec = {c: "{:.4f}" for c in display_cols if c not in ["Model"]}

            # Sort by ROC AUC descending
            sort_col = "ROC AUC" if "ROC AUC" in comp_df.columns else display_cols[1]
            comp_df_disp = comp_df[display_cols].sort_values(sort_col, ascending=False)

            st.dataframe(
                comp_df_disp.style.format(format_spec, na_rep="—"),
                use_container_width=True,
                hide_index=True,
            )

            # Bar chart — grouped by metric
            numeric_cols = [c for c in ["ROC AUC", "F1 (Weighted)", "Accuracy"] if c in comp_df.columns]
            if numeric_cols:
                fig_comp = go.Figure()
                model_col = "Model" if "Model" in comp_df.columns else "model_name"
                for col in numeric_cols:
                    fig_comp.add_trace(go.Bar(
                        name=col,
                        x=comp_df[model_col],
                        y=comp_df[col],
                        text=comp_df[col].round(4),
                        textposition="outside",
                    ))
                fig_comp.update_layout(
                    title="Model Performance Metrics",
                    barmode="group",
                    paper_bgcolor="rgba(0,0,0,0)",
                    plot_bgcolor="rgba(30,41,59,0.6)",
                    font=dict(color="#f8fafc"),
                    legend=dict(orientation="h", y=1.1),
                )
                st.plotly_chart(fig_comp, use_container_width=True)
    else:
        st.info("Run `python train_all_models.py` to generate model comparison metrics.")

    # ── Confusion Matrix ──────────────────────────────────────────────────────
    st.markdown("### 🎯 Confusion Matrix")
    cm_path = REPORTS_DIR / "confusion_matrix.png"
    if cm_path.exists():
        st.image(str(cm_path), caption="Confusion Matrix — Best ML Model", use_container_width=True)
    else:
        st.info("Run `python src/model_comparison.py` to generate the confusion matrix.")

    # ── Classification Report ─────────────────────────────────────────────────
    st.markdown("### 📋 Classification Report")
    cr_path = REPORTS_DIR / "classification_report.csv"
    if cr_path.exists():
        cr_df = pd.read_csv(cr_path, index_col=0)
        numeric_cols = cr_df.select_dtypes(include=['float64', 'int64']).columns
        st.dataframe(
            cr_df.style.format(subset=numeric_cols, formatter="{:.4f}", na_rep="—").background_gradient(
                subset=["precision", "recall", "f1-score"], cmap="Blues"
            ),
            use_container_width=True,
        )
    else:
        st.info("Classification report not found. Run `python src/model_comparison.py`.")

    # ── ANN Training History ──────────────────────────────────────────────────
    st.markdown("### 🧠 ANN Training History")

    tab_acc, tab_loss, tab_saved = st.tabs(["Accuracy Curve", "Loss Curve", "Saved Plots"])

    with tab_acc:
        if HEALTH_IMPACT_ANN_HISTORY_PATH.exists():
            with open(HEALTH_IMPACT_ANN_HISTORY_PATH, "r") as f:
                history = json.load(f)
            epochs = list(range(1, history["epochs_run"] + 1))
            fig_acc = go.Figure()
            fig_acc.add_trace(go.Scatter(x=epochs, y=history["accuracy"], name="Train Acc",
                                          line=dict(color="#00d4aa", width=2)))
            fig_acc.add_trace(go.Scatter(x=epochs, y=history["val_accuracy"], name="Val Acc",
                                          line=dict(color="#f59e0b", width=2, dash="dash")))
            fig_acc.update_layout(
                title="ANN Training & Validation Accuracy",
                xaxis_title="Epoch", yaxis_title="Accuracy",
                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(30,41,59,0.6)",
                font=dict(color="#f8fafc"), hovermode="x unified",
            )
            st.plotly_chart(fig_acc, use_container_width=True)
        else:
            st.info("ANN history not found.")

    with tab_loss:
        if HEALTH_IMPACT_ANN_HISTORY_PATH.exists():
            with open(HEALTH_IMPACT_ANN_HISTORY_PATH, "r") as f:
                history = json.load(f)
            epochs = list(range(1, history["epochs_run"] + 1))
            fig_loss = go.Figure()
            fig_loss.add_trace(go.Scatter(x=epochs, y=history["loss"], name="Train Loss",
                                           line=dict(color="#ef4444", width=2)))
            fig_loss.add_trace(go.Scatter(x=epochs, y=history["val_loss"], name="Val Loss",
                                           line=dict(color="#f59e0b", width=2, dash="dash")))
            fig_loss.update_layout(
                title="ANN Training & Validation Loss",
                xaxis_title="Epoch", yaxis_title="Cross-Entropy Loss",
                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(30,41,59,0.6)",
                font=dict(color="#f8fafc"), hovermode="x unified",
            )
            st.plotly_chart(fig_loss, use_container_width=True)
        else:
            st.info("ANN history not found.")

    with tab_saved:
        saved_plots = {
            "Accuracy Curve": REPORTS_DIR / "accuracy_curve.png",
            "Loss Curve": REPORTS_DIR / "loss_curve.png",
            "ROC Curve": REPORTS_DIR / "roc_curve.png",
            "Learning Curve": REPORTS_DIR / "learning_curve.png",
        }
        any_found = False
        for plot_name, plot_path in saved_plots.items():
            if plot_path.exists():
                st.image(str(plot_path), caption=plot_name, use_container_width=True)
                any_found = True
        if not any_found:
            st.info("No saved plots yet. Run `python src/model_comparison.py` to generate them.")

    # ── Metric bar images ─────────────────────────────────────────────────────
    st.markdown("### 📊 Metric Comparison Plots")
    metric_plots = {
        "Accuracy": REPORTS_DIR / "model_accuracy_comparison.png",
        "Precision": REPORTS_DIR / "model_precision_comparison.png",
        "Recall":   REPORTS_DIR / "model_recall_comparison.png",
        "F1 Score": REPORTS_DIR / "model_f1_comparison.png",
    }
    plot_cols = st.columns(2)
    for idx, (plot_name, plot_path) in enumerate(metric_plots.items()):
        with plot_cols[idx % 2]:
            if plot_path.exists():
                st.image(str(plot_path), caption=plot_name, use_container_width=True)

st.markdown("---")

# ─── Model selector ───────────────────────────────────────────────────────────
st.markdown("### 🤖 Select Prediction Model")

model_options = []
if model_ready:
    model_options.append("🏆 Best ML Model (Auto-Selected)")
if ann_ready:
    model_options.append("🧠 ANN (Deep Learning — PyTorch)")
if not model_options:
    model_options.append("No models available")

selected_model_label = st.radio(
    "Choose which model to use for prediction:",
    model_options,
    horizontal=True,
    label_visibility="collapsed",
)
use_ann = "ANN" in selected_model_label

if use_ann and not ann_ready:
    st.error("⚠️ ANN artifacts not found. Run: `python src/health_impact_dl_model.py`")
elif not use_ann and not model_ready:
    st.error("⚠️ ML model not found. Run: `python src/health_impact_model.py`")

st.markdown("---")
st.markdown("### 🔢 Enter Health & Environmental Parameters")

# ─── Preset buttons ───────────────────────────────────────────────────────────
col_p1, col_p2 = st.columns(2)
with col_p1:
    if st.button("📋 Load High-Risk Example"):
        st.session_state.update({
            "hi_aqi": 280.0, "hi_pm10": 154.0, "hi_pm25": 105.0,
            "hi_no2": 105.0, "hi_so2": 50.0, "hi_o3": 154.0,
            "hi_temp": 15.0, "hi_hum": 55.0, "hi_wind": 10.0,
            "hi_resp": 10.0, "hi_cardio": 5.0, "hi_hosp": 2.0,
            "hi_score": 98.0,
        })
with col_p2:
    if st.button("✅ Load Low-Risk Example"):
        st.session_state.update({
            "hi_aqi": 90.0, "hi_pm10": 113.0, "hi_pm25": 62.0,
            "hi_no2": 85.0, "hi_so2": 49.0, "hi_o3": 118.0,
            "hi_temp": 16.0, "hi_hum": 52.0, "hi_wind": 10.0,
            "hi_resp": 10.0, "hi_cardio": 5.0, "hi_hosp": 2.0,
            "hi_score": 62.0,
        })

st.markdown("<br>", unsafe_allow_html=True)

# ─── Input fields ─────────────────────────────────────────────────────────────
c1, c2, c3 = st.columns(3)

with c1:
    st.markdown("**🌫️ Air Quality**")
    hi_aqi  = st.number_input("AQI", 0.0, 500.0, float(st.session_state.get("hi_aqi", 100.0)), 1.0, key="hi_aqi")
    hi_pm10 = st.number_input("PM₁₀ (µg/m³)", 0.0, 1000.0, float(st.session_state.get("hi_pm10", 80.0)), 1.0, key="hi_pm10")
    hi_pm25 = st.number_input("PM₂.₅ (µg/m³)", 0.0, 500.0, float(st.session_state.get("hi_pm25", 40.0)), 0.1, key="hi_pm25")
    hi_no2  = st.number_input("NO₂ (µg/m³)", 0.0, 500.0, float(st.session_state.get("hi_no2", 50.0)), 1.0, key="hi_no2")
    hi_so2  = st.number_input("SO₂ (µg/m³)", 0.0, 500.0, float(st.session_state.get("hi_so2", 20.0)), 1.0, key="hi_so2")

with c2:
    st.markdown("**🌡️ Weather**")
    hi_o3   = st.number_input("O₃ (µg/m³)", 0.0, 300.0, float(st.session_state.get("hi_o3", 60.0)), 1.0, key="hi_o3")
    hi_temp = st.number_input("Temperature (°C)", -30.0, 60.0, float(st.session_state.get("hi_temp", 25.0)), 0.5, key="hi_temp")
    hi_hum  = st.number_input("Humidity (%)", 0.0, 100.0, float(st.session_state.get("hi_hum", 60.0)), 1.0, key="hi_hum")
    hi_wind = st.number_input("Wind Speed (m/s)", 0.0, 50.0, float(st.session_state.get("hi_wind", 5.0)), 0.1, key="hi_wind")

with c3:
    st.markdown("**🏥 Health Metrics**")
    hi_resp   = st.number_input("Respiratory Cases", 0.0, 10000.0, float(st.session_state.get("hi_resp", 100.0)), 1.0, key="hi_resp")
    hi_cardio = st.number_input("Cardiovascular Cases", 0.0, 5000.0, float(st.session_state.get("hi_cardio", 50.0)), 1.0, key="hi_cardio")
    hi_hosp   = st.number_input("Hospital Admissions", 0.0, 5000.0, float(st.session_state.get("hi_hosp", 20.0)), 1.0, key="hi_hosp")
    hi_score  = st.number_input("Health Impact Score", 0.0, 500.0, float(st.session_state.get("hi_score", 50.0)), 0.5, key="hi_score")

inputs = {
    "AQI": hi_aqi, "PM10": hi_pm10, "PM2_5": hi_pm25,
    "NO2": hi_no2, "SO2": hi_so2, "O3": hi_o3,
    "Temperature": hi_temp, "Humidity": hi_hum, "WindSpeed": hi_wind,
    "RespiratoryCases": hi_resp, "CardiovascularCases": hi_cardio,
    "HospitalAdmissions": hi_hosp, "HealthImpactScore": hi_score,
}

st.markdown("<br>", unsafe_allow_html=True)
predict_ready = (use_ann and ann_ready) or (not use_ann and model_ready)
predict_btn = st.button(
    "🔍 Predict Health Impact",
    disabled=not predict_ready,
    use_container_width=True,
)

# ─── Prediction Results ───────────────────────────────────────────────────────
if predict_btn and predict_ready:
    valid, errors = validate_health_inputs(inputs)
    if errors and any("must" in e for e in errors):
        st.error(format_validation_errors(errors))
    else:
        if errors:
            for e in errors:
                if "⚠️" in e:
                    st.warning(e)

        with st.spinner("Running health impact prediction..."):
            try:
                if use_ann:
                    # ── ANN prediction path ──────────────────────────────────
                    from utils.model_utils import predict_with_ann as _pw_ann
                    ann_model = ann_arts["model"]
                    ann_preprocessor = ann_arts["preprocessor"]
                    ann_config = ann_arts["config"]

                    feature_names = getattr(
                        ann_preprocessor, "feature_names",
                        ann_config.get("feature_names", list(inputs.keys()))
                    )
                    row = {f: inputs.get(f, 0.0) for f in feature_names}
                    X_df = pd.DataFrame([row])
                    X_scaled = ann_preprocessor.transform(X_df)

                    y_pred_arr, y_proba_arr = _pw_ann(ann_model, X_scaled)
                    pred_enc = int(y_pred_arr[0])
                    proba = y_proba_arr[0]

                    class_names = ann_config.get(
                        "class_names",
                        list(ann_preprocessor.label_encoder.classes_)
                    )
                    pred_class = ann_preprocessor.label_encoder.inverse_transform([pred_enc])[0]
                    confidence = float(np.max(proba)) * 100
                    used_model_name = "ANN (PyTorch Deep Learning)"

                else:
                    # ── ML prediction path ───────────────────────────────────
                    model = arts["model"]
                    scaler = arts["scaler"]
                    encoder = arts["encoder"]

                    X = pd.DataFrame([inputs])
                    if hasattr(scaler, "feature_names_in_"):
                        X = X[list(scaler.feature_names_in_)]
                    X_scaled = scaler.transform(X)

                    pred_enc = model.predict(X_scaled)[0]
                    proba_raw = (
                        model.predict_proba(X_scaled)[0]
                        if hasattr(model, "predict_proba") else None
                    )
                    pred_class = encoder.inverse_transform([pred_enc])[0]
                    class_names = list(encoder.classes_)
                    proba = proba_raw if proba_raw is not None else np.array([])
                    confidence = float(np.max(proba)) * 100 if len(proba) else 0.0
                    used_model_name = type(model).__name__

            except Exception as exc:
                st.error(f"Prediction failed: {exc}")
                st.stop()

        # Save to session
        st.session_state["health_impact_result"] = {
            "prediction": pred_class,
            "confidence": confidence / 100,
            "probabilities": dict(zip(class_names, proba.tolist())) if len(proba) else {},
            "inputs": inputs,
            "model_used": used_model_name,
        }

        st.markdown("---")
        st.markdown("### 🎯 Health Impact Prediction Results")

        # Model used badge
        badge_color = "#7c3aed" if use_ann else "#00d4aa"
        badge_label = "Deep Learning" if use_ann else "Machine Learning"
        st.markdown(
            f"<div style='display:inline-block;background:{badge_color}22;border:1px solid {badge_color}66;"
            f"border-radius:20px;padding:0.25rem 0.9rem;font-size:0.82rem;color:{badge_color};margin-bottom:1rem;'>"
            f"🤖 Prediction via: <strong>{used_model_name}</strong> ({badge_label})</div>",
            unsafe_allow_html=True,
        )

        r1, r2 = st.columns([1, 1])

        RISK_COLORS = {
            "Low": "#22c55e", "Moderate": "#eab308",
            "High": "#f97316", "Severe": "#ef4444", "Very High": "#dc2626"
        }
        pred_color = RISK_COLORS.get(pred_class, "#94a3b8")

        with r1:
            st.markdown(f"""
            <div style='text-align:center; padding:2rem;
                        background:rgba(30,41,59,0.8);border-radius:16px;border:1px solid {pred_color}44;'>
                <div style='font-size:3rem; margin-bottom:0.5rem;'>🫁</div>
                <div style='font-size:1rem; color:#94a3b8; text-transform:uppercase; letter-spacing:0.1em;'>
                    Predicted Health Impact
                </div>
                <div style='font-size:2.5rem; font-weight:700; color:{pred_color}; margin:0.5rem 0;'>
                    {pred_class}
                </div>
                <div style='color:#94a3b8; font-size:1rem;'>
                    Confidence: <strong style='color:#00d4aa;'>{confidence:.1f}%</strong>
                </div>
            </div>
            """, unsafe_allow_html=True)

        with r2:
            if len(proba) > 0:
                st.plotly_chart(
                    plot_prediction_probabilities(proba, class_names),
                    use_container_width=True,
                )

        st.markdown("---")

        # ── Health interpretation ─────────────────────────────────────────────
        st.markdown("### 📋 Health Risk Interpretation")
        interp_messages = {
            "Low": ("✅ Low Health Risk", "#22c55e",
                    "Air quality is within acceptable limits. Minimal health risk for the general population. Continue monitoring."),
            "Moderate": ("⚠️ Moderate Health Risk", "#eab308",
                         "Sensitive groups (children, elderly, people with respiratory conditions) may experience mild symptoms. Reduce prolonged outdoor exposure."),
            "High": ("🔔 High Health Risk", "#f97316",
                     "General population may experience health effects. Limit outdoor activities, especially vigorous exercise. Sensitive groups should avoid outdoor exposure."),
            "Severe": ("🚨 Severe Health Risk", "#ef4444",
                       "Everyone should avoid outdoor activities. Serious health effects are likely. Stay indoors with filtered air. Seek medical attention if symptoms develop."),
            "Very High": ("🚨 Very High Health Risk", "#dc2626",
                          "HEALTH EMERGENCY. Avoid all outdoor exposure. High probability of serious health consequences across the general population."),
        }

        msg_title, msg_color, msg_text = interp_messages.get(
            pred_class, ("⚠️ Unknown Risk", "#94a3b8", "Class not recognized.")
        )

        st.markdown(f"""
        <div style='background:rgba(30,41,59,0.8); border:2px solid {msg_color}44;
                    border-radius:16px; padding:1.5rem; margin:1rem 0;'>
            <h3 style='color:{msg_color}; margin-top:0;'>{msg_title}</h3>
            <p style='color:#f8fafc;'>{msg_text}</p>
        </div>
        """, unsafe_allow_html=True)

        c_vuln, c_prec = st.columns(2)
        with c_vuln:
            st.markdown("""
            **👥 Vulnerable Populations:**
            - 👶 Children under 14
            - 👴 Elderly (65+)
            - 🫁 Asthma / COPD patients
            - ❤️ Cardiovascular disease patients
            - 🤰 Pregnant women
            """)
        with c_prec:
            st.markdown(f"""
            **🛡️ Recommended Precautions:**
            - {'🚫 Avoid all outdoor activities' if pred_class in ('Severe', 'Very High') else '⚠️ Limit prolonged outdoor exposure'}
            - {'😷 Wear N95/FFP2 mask outdoors' if pred_class in ('High', 'Severe', 'Very High') else '😷 Consider a mask in crowded areas'}
            - 🏠 Keep windows closed during peak pollution
            - 💧 Stay well hydrated
            - {'🏥 Seek medical attention if symptoms develop' if pred_class in ('Severe', 'Very High') else '📞 Consult doctor if concerned'}
            """)

        # Repeat disclaimer
        st.markdown("""
        ---
        <div style='background:rgba(239,68,68,0.1); border:1px solid rgba(239,68,68,0.4);
                    border-radius:12px; padding:1rem; font-size:0.85rem; color:#fca5a5;'>
            ⚠️ <strong>Reminder:</strong> These predictions are analytical estimates only.
            They are NOT medical diagnoses. Consult a healthcare professional for medical advice.
        </div>
        """, unsafe_allow_html=True)
