"""
Page 4 — Health Impact Assessment
Multi-class health impact prediction with prominent medical disclaimer.
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pandas as pd
import streamlit as st

from utils.config import HEALTH_IMPACT_FEATURES, COLORS
from utils.config import HEALTH_IMPACT_MODEL_PATH, HEALTH_IMPACT_SCALER_PATH, HEALTH_IMPACT_ENCODER_PATH
from utils.validators import validate_health_inputs, format_validation_errors
from utils.visualization import plot_prediction_probabilities
from utils.model_utils import load_model

st.set_page_config(page_title="Health Impact — EIA", page_icon="🫁", layout="wide")
css_path = Path(__file__).parent.parent / "assets" / "css" / "style.css"
if css_path.exists():
    with open(css_path) as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)


@st.cache_resource
def get_health_artifacts():
    return {
        "model": load_model(HEALTH_IMPACT_MODEL_PATH, "health_impact_model"),
        "scaler": load_model(HEALTH_IMPACT_SCALER_PATH, "health_impact_scaler"),
        "encoder": load_model(HEALTH_IMPACT_ENCODER_PATH, "health_impact_encoder"),
    }


# ─── Header ──────────────────────────────────────────────────────────────────
st.markdown("""
<div class='page-header'>
    <h1 class='page-title'>🫁 Health Impact Assessment</h1>
    <p class='page-subtitle'>Predict health risk category from air quality and environmental parameters</p>
</div>
""", unsafe_allow_html=True)

# ─── MANDATORY HEALTH DISCLAIMER ─────────────────────────────────────────────
st.markdown("""
<div class='health-disclaimer'>
    <h3 style='color:#f87171; margin-top:0;'>⚠️ IMPORTANT HEALTH & MEDICAL DISCLAIMER</h3>
    <p>The Health Impact predictions generated by this application are:</p>
    <ul>
        <li>📊 <strong>ANALYTICAL ESTIMATES</strong> based on air quality data ONLY</li>
        <li>❌ <strong>NOT</strong> medical diagnoses or professional medical advice</li>
        <li>❌ <strong>NOT</strong> a substitute for consultation with healthcare professionals</li>
        <li>⚠️ Subject to model limitations and data quality issues</li>
    </ul>
    <p><strong>This application should NOT be used for:</strong></p>
    <ul>
        <li>✗ Making medical decisions without professional consultation</li>
        <li>✗ Diagnosing health conditions</li>
        <li>✗ Replacing professional medical advice</li>
    </ul>
    <p style='color:#fca5a5; font-weight:600; margin-bottom:0;'>
        ✓ Use predictions as a general environmental awareness tool only.<br>
        ✓ Always consult qualified healthcare professionals for medical decisions.
    </p>
</div>
""", unsafe_allow_html=True)

arts = get_health_artifacts()
model_ready = arts["model"] is not None

if not model_ready:
    st.warning("⏳ Health Impact model not found. Please run: `python src/health_impact_model.py`")

# ─── Model Info ───────────────────────────────────────────────────────────────
with st.expander("ℹ️ About This Model", expanded=False):
    st.markdown("""
    Four models were trained and compared. The best model was selected by ROC-AUC score.
    
    | Model | Notes |
    |-------|-------|
    | Logistic Regression | Baseline; interpretable |
    | Decision Tree | Interpretable; may overfit |
    | Random Forest | Ensemble; robust |
    | **XGBoost** | **Best performer expected** |
    
    **Evaluation:** 5-fold stratified CV · Accuracy · F1 · ROC-AUC  
    **Target:** HealthImpactClass (multi-class or binary depending on data)
    """)

st.markdown("---")
st.markdown("### 🔢 Enter Health & Environmental Parameters")

# Preset
col_p1, col_p2 = st.columns(2)
with col_p1:
    if st.button("📋 Load High-Risk Example"):
        st.session_state.update({
            "hi_aqi": 200.0, "hi_pm10": 300.0, "hi_pm25": 150.0,
            "hi_no2": 180.0, "hi_so2": 120.0, "hi_o3": 160.0,
            "hi_temp": 35.0, "hi_hum": 80.0, "hi_wind": 2.0,
            "hi_resp": 500.0, "hi_cardio": 200.0, "hi_hosp": 100.0,
            "hi_score": 90.0,
        })
with col_p2:
    if st.button("✅ Load Low-Risk Example"):
        st.session_state.update({
            "hi_aqi": 30.0, "hi_pm10": 20.0, "hi_pm25": 8.0,
            "hi_no2": 15.0, "hi_so2": 5.0, "hi_o3": 40.0,
            "hi_temp": 22.0, "hi_hum": 50.0, "hi_wind": 8.0,
            "hi_resp": 50.0, "hi_cardio": 20.0, "hi_hosp": 5.0,
            "hi_score": 15.0,
        })

st.markdown("<br>", unsafe_allow_html=True)

# Inputs in 3 columns
c1, c2, c3 = st.columns(3)

with c1:
    st.markdown("**🌫️ Air Quality**")
    hi_aqi = st.number_input("AQI", 0.0, 500.0, float(st.session_state.get("hi_aqi", 100.0)), 1.0, key="hi_aqi")
    hi_pm10 = st.number_input("PM₁₀ (µg/m³)", 0.0, 1000.0, float(st.session_state.get("hi_pm10", 80.0)), 1.0, key="hi_pm10")
    hi_pm25 = st.number_input("PM₂.₅ (µg/m³)", 0.0, 500.0, float(st.session_state.get("hi_pm25", 40.0)), 0.1, key="hi_pm25")
    hi_no2 = st.number_input("NO₂ (µg/m³)", 0.0, 500.0, float(st.session_state.get("hi_no2", 50.0)), 1.0, key="hi_no2")
    hi_so2 = st.number_input("SO₂ (µg/m³)", 0.0, 500.0, float(st.session_state.get("hi_so2", 20.0)), 1.0, key="hi_so2")

with c2:
    st.markdown("**🌡️ Weather**")
    hi_o3 = st.number_input("O₃ (µg/m³)", 0.0, 300.0, float(st.session_state.get("hi_o3", 60.0)), 1.0, key="hi_o3")
    hi_temp = st.number_input("Temperature (°C)", -30.0, 60.0, float(st.session_state.get("hi_temp", 25.0)), 0.5, key="hi_temp")
    hi_hum = st.number_input("Humidity (%)", 0.0, 100.0, float(st.session_state.get("hi_hum", 60.0)), 1.0, key="hi_hum")
    hi_wind = st.number_input("Wind Speed (m/s)", 0.0, 50.0, float(st.session_state.get("hi_wind", 5.0)), 0.1, key="hi_wind")

with c3:
    st.markdown("**🏥 Health Metrics**")
    hi_resp = st.number_input("Respiratory Cases", 0.0, 10000.0, float(st.session_state.get("hi_resp", 100.0)), 1.0, key="hi_resp")
    hi_cardio = st.number_input("Cardiovascular Cases", 0.0, 5000.0, float(st.session_state.get("hi_cardio", 50.0)), 1.0, key="hi_cardio")
    hi_hosp = st.number_input("Hospital Admissions", 0.0, 5000.0, float(st.session_state.get("hi_hosp", 20.0)), 1.0, key="hi_hosp")
    hi_score = st.number_input("Health Impact Score", 0.0, 500.0, float(st.session_state.get("hi_score", 50.0)), 0.5, key="hi_score")

inputs = {
    "AQI": hi_aqi, "PM10": hi_pm10, "PM2_5": hi_pm25,
    "NO2": hi_no2, "SO2": hi_so2, "O3": hi_o3,
    "Temperature": hi_temp, "Humidity": hi_hum, "WindSpeed": hi_wind,
    "RespiratoryCases": hi_resp, "CardiovascularCases": hi_cardio,
    "HospitalAdmissions": hi_hosp, "HealthImpactScore": hi_score,
}

st.markdown("<br>", unsafe_allow_html=True)
predict_btn = st.button("🔍 Predict Health Impact", disabled=not model_ready, use_container_width=True)

# ─── Prediction Results ────────────────────────────────────────────────────────
if predict_btn and model_ready:
    valid, errors = validate_health_inputs(inputs)
    if errors and any("must" in e for e in errors):  # hard errors only
        st.error(format_validation_errors(errors))
    else:
        if errors:
            for e in errors:
                if "⚠️" in e:
                    st.warning(e)

        with st.spinner("Running health impact prediction..."):
            model = arts["model"]
            scaler = arts["scaler"]
            encoder = arts["encoder"]

            X = pd.DataFrame([inputs])
            X_scaled = scaler.transform(X)
            pred_enc = model.predict(X_scaled)[0]
            proba = model.predict_proba(X_scaled)[0] if hasattr(model, "predict_proba") else None
            pred_class = encoder.inverse_transform([pred_enc])[0]
            confidence = float(max(proba)) * 100 if proba is not None else 0
            class_names = list(encoder.classes_)

        # Save to session
        st.session_state["health_impact_result"] = {
            "prediction": pred_class,
            "confidence": confidence / 100,
            "probabilities": dict(zip(class_names, proba.tolist())) if proba is not None else {},
            "inputs": inputs,
        }

        st.markdown("---")
        st.markdown("### 🎯 Health Impact Prediction Results")

        r1, r2 = st.columns([1, 1])

        RISK_COLORS = {
            "Low": "#22c55e", "Moderate": "#eab308",
            "High": "#f97316", "Severe": "#ef4444", "Very High": "#dc2626"
        }
        pred_color = RISK_COLORS.get(pred_class, "#94a3b8")

        with r1:
            st.markdown(f"""
            <div style='text-align:center; padding:2rem;
                        background:rgba(30,41,59,0.8);border-radius:16px;border:1px solid {pred_color}44;'>
                <div style='font-size:3rem; margin-bottom:0.5rem;'>🫁</div>
                <div style='font-size:1rem; color:#94a3b8; text-transform:uppercase; letter-spacing:0.1em;'>
                    Predicted Health Impact
                </div>
                <div style='font-size:2.5rem; font-weight:700; color:{pred_color}; margin:0.5rem 0;'>
                    {pred_class}
                </div>
                <div style='color:#94a3b8; font-size:1rem;'>
                    Confidence: <strong style='color:#00d4aa;'>{confidence:.1f}%</strong>
                </div>
            </div>
            """, unsafe_allow_html=True)

        with r2:
            if proba is not None:
                st.plotly_chart(
                    plot_prediction_probabilities(proba, class_names),
                    use_container_width=True
                )

        st.markdown("---")

        # Health interpretation
        st.markdown("### 📋 Health Risk Interpretation")
        interp_messages = {
            "Low": ("✅ Low Health Risk", "#22c55e",
                    "Air quality is within acceptable limits. Minimal health risk for the general population. Continue monitoring."),
            "Moderate": ("⚠️ Moderate Health Risk", "#eab308",
                         "Sensitive groups (children, elderly, people with respiratory conditions) may experience mild symptoms. Reduce prolonged outdoor exposure."),
            "High": ("🔔 High Health Risk", "#f97316",
                     "General population may experience health effects. Limit outdoor activities, especially vigorous exercise. Sensitive groups should avoid outdoor exposure."),
            "Severe": ("🚨 Severe Health Risk", "#ef4444",
                       "Everyone should avoid outdoor activities. Serious health effects are likely. Stay indoors with filtered air. Seek medical attention if symptoms develop."),
            "Very High": ("🚨 Very High Health Risk", "#dc2626",
                          "HEALTH EMERGENCY. Avoid all outdoor exposure. High probability of serious health consequences across the general population."),
        }

        msg_title, msg_color, msg_text = interp_messages.get(
            pred_class, ("⚠️ Unknown Risk", "#94a3b8", "Class not recognized.")
        )

        st.markdown(f"""
        <div style='background:rgba(30,41,59,0.8); border:2px solid {msg_color}44;
                    border-radius:16px; padding:1.5rem; margin:1rem 0;'>
            <h3 style='color:{msg_color}; margin-top:0;'>{msg_title}</h3>
            <p style='color:#f8fafc;'>{msg_text}</p>
        </div>
        """, unsafe_allow_html=True)

        # Vulnerable populations
        c_vuln, c_prec = st.columns(2)
        with c_vuln:
            st.markdown("""
            **👥 Vulnerable Populations:**
            - 👶 Children under 14
            - 👴 Elderly (65+)
            - 🫁 Asthma / COPD patients
            - ❤️ Cardiovascular disease patients
            - 🤰 Pregnant women
            """)
        with c_prec:
            st.markdown(f"""
            **🛡️ Recommended Precautions:**
            - {'🚫 Avoid all outdoor activities' if pred_class in ('Severe', 'Very High') else '⚠️ Limit prolonged outdoor exposure'}
            - {'😷 Wear N95/FFP2 mask outdoors' if pred_class in ('High', 'Severe', 'Very High') else '😷 Consider a mask in crowded areas'}
            - 🏠 Keep windows closed during peak pollution
            - 💧 Stay well hydrated
            - {'🏥 Seek medical attention if symptoms develop' if pred_class in ('Severe', 'Very High') else '📞 Consult doctor if concerned'}
            """)

        # Repeat disclaimer
        st.markdown("""
        ---
        <div style='background:rgba(239,68,68,0.1); border:1px solid rgba(239,68,68,0.4);
                    border-radius:12px; padding:1rem; font-size:0.85rem; color:#fca5a5;'>
            ⚠️ <strong>Reminder:</strong> These predictions are analytical estimates only.
            They are NOT medical diagnoses. Consult a healthcare professional for medical advice.
        </div>
        """, unsafe_allow_html=True)
